version: '2'
services:
  mavros:
    extends:
      file: ../services/mavros/mavros.yml
      service: mavros
    env_file:
      - ./ros.env
  pozyx:
    extends:
      file: ../services/pozyx/pozyx.yml
      service: pozyx
    env_file:
      - ./ros.env
  xbee:
    extends:
      file: ../services/xbee/xbee.yml
      service: xbee
    env_file:
      - ./ros.env
  monitor:
    extends:
      file: ../services/monitor/monitor.yml
      service: monitor
    env_file:
      - ./ros.env
