version: '2'
services:
  mavros:
    extends:
      file: ../services/mavros/mavros.yml
      service: mavros
    env_file:
      - ./ros.env
  pozyx:
    extends:
      file: ../services/pozyx/pozyx.yml
      service: pozyx
    env_file:
      - ./ros.env
  optitrack:
    extends:
      file: ../services/optitrack/optitrack.yml
      service: optitrack
    env_file:
      - ./ros.env
