version: '2'
services:
  led:
     image: jeguzzi/df:armhf-gps
     command: roslaunch launch/gps-ublox.launch
     volumes:
       - ../../logs:/root/.ros/log:rw
       - ./lawa-drone.py.launch:/root/catkin_ws/lawa/script/lawa-drone.py:ro
       - ./lawa.launch.launch:/root/catkin_ws/lawa/launch/lawa.launch:ro
     privileged: true
     network_mode: host
