version: '2'
services:
  xbee:
    image: jeguzzi/df:armhf-mavlink-limiter
    command: roslaunch mavlink_limiter main.launch gcs_url:=serial:///dev/ttyUSB0
    privileged: true
    network_mode: host
    volumes:
      - ../../logs:/root/.ros/log:rw
      - ./limiter.launch:/root/catkin_ws/src/mavlink_limiter/launch/main.launch:ro
      - ./rates.config:/root/catkin_ws/src/mavlink_limiter/config/rates.config:ro
