version: '2'
services:
  monitor:
    image: jeguzzi/df:armhf-docker-ui
    command: roslaunch docker_ui monitor.launch video:=true video_stream:=/camera/image/compressed
    privileged: true
    volumes:
      - ../logs:/root/.ros/log:rw
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    environment:
      - "ifaces=['wlan0']"
