version: '2'
services:
  mavros:
    extends:
      file: ../services/mavros/mavros.yml
      service: mavros
    env_file:
      - ./ros.env
    restart: always
  pozyx:
    extends:
      file: ../services/pozyx/pozyx.yml
      service: pozyx
    env_file:
      - ./ros.env
    restart: always
  optitrack:
    extends:
      file: ../services/optitrack/optitrack_passive.yml
      service: optitrack
    env_file:
      - ./ros.env
    restart: always
